### ISSUE TITLE
jQuery 3.4.1 vulnerabilities

### ISSUE THREAD

**Issue by dmlemos** [ClearURLs/Addon#166]
First of all, thanks for making this extension.

I'd like to let you know that the `jquery v3.4.1.min` ​being used has a couple medium vulnerabilities. Report's here:
https://crxcavator.io/report/lckanjgmijmafbedllaakclkaicjfmnk?platform=Chrome&new_scan=true

These were fixed in [jQuery 3.5.0](https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/)

**Comment by KevinRoebert** [comment]
Thank you for the report. Please always send security-relevant reports by mail (support (at) clearurls.xyz), so that the maintainer has time to react and not all users are potentially at risk.

ClearURLs is not affected by the vulnerability as far as I know. We use jQuery only inside the log page because it is a hard dependency of DataTables. Since the vulnerability is an XSS attack using RegExp, I don't see any exposure right now.

Nevertheless, I have updated the jQuery to 3.6.0. The latest ClearURLs version is already in review at Mozilla, Google, and Microsoft.

**Comment by dmlemos** [comment]
I appreciate the quick fix, even though it doesn't seem to be needed.

> Thank you for the report. Please always send security-relevant reports by mail (support (at) clearurls.xyz), so that the maintainer has time to react and not all users are potentially at risk.

It is a very sensible advise, which I will keep in mind for the future. Apologies this time.
