### ISSUE TITLE
Where is the extension hosted (GitHub or GitLab)?

### ISSUE THREAD

**Issue by vishalnandagopal** [ClearURLs/Addon#176]
When I tried to search for the extension repository to report the extension, I found the same project on [GitHub](https://github.com/ClearURLs/Addon/issues/new) and [GitLab](https://gitlab.com/KevinRoebert/ClearUrls).

Which is the official repo of the addon? Both seem to be official, and all commits are identical.

Do you maintain the same extension on two sites, and can users report issues or bugs on any of these two sites?

**Comment by KevinRoebert** [comment]
> Which is the official repo of the addon?

-  https://gitlab.com/ClearURLs/rules: official repo of the rules for the addon.
- https://gitlab.com/KevinRoebert/ClearUrls: official repo of the addon

 > Both seem to be official, and all commits are identical.

The GitHub repo is a mirror of the GitLab repo.

> Do you maintain the same extension on two sites

Yes

> and can users report issues or bugs on any of these two sites?

Yes

However, due to the mirror status, only pull requests can be directly merged from GitLab. Pull requests on GitHub have to be merged manually and locally into the master branch.

Issues, bug reports, and pull requests are accepted on both platforms.

**Comment by vishalnandagopal** [comment]
Okay. Thanks for clarifying!
