### ISSUE TITLE
Vivaldi + Gmail document preview kills loading of every other website

### ISSUE THREAD

**Issue by akulumbeg** [ClearURLs/Addon#186]
In the Vivaldi browser 5.1.2567.66 (Win 11 Pro x64), after the update of ClearURLs to 1.23.0, opening a multipage docx document preview in Gmail results in the second page not loading and additionally, killing all connections. No website can load, no video can load nor play, etc. Restarting the browser solves it, however the issue persists. The issue does not appear when the plugin is disabled.

**Comment by KevinRoebert** [comment]
Maybe related to https://github.com/ClearURLs/Addon/issues/185

Could you please provide a log?

**Comment by akulumbeg** [comment]
Here's a gist with the exported JSON. 

https://gist.github.com/akulumbeg/d237797043d09d5554f5fe653beda5fe

I found out that when the crash occurs, the extensions' GUI also gets disabled, so getting a log is quite difficult. This is the best I got, last 25 entries, top -> bottom = oldest -> newest.

**Comment by KevinRoebert** [comment]
I'm not entirely sure, but the problem could be the history API protection. I haven't changed anything regarding the actual cleanup function of ClearURLs since version 1.22.0. A helper script that is not used by the core module of ClearURLs, but by side functions like history API protection, I've added a recursive cleaning function. Possibly clean links are converted back to unclean links on-the-fly from certain pages. Then there would be an infinite loop.

So, could you try turning off **history API protection** and see if the problem still occurs?

If not, I would know where the problem comes from, but not yet how best to solve it.

**Comment by akulumbeg** [comment]
Good guess! I can confirm that the upon disabling the _Prevent tracking injection over history API_ option in the settings fixes the problem.

**Comment by KevinRoebert** [comment]
[185](https://github.com/ClearURLs/Addon/issues/185) and [186](https://github.com/ClearURLs/Addon/issues/186) are duplicate.

I will close this one.
