### ISSUE TITLE
[bug] ClearURLs will break a lot of popular websites

### ISSUE THREAD

**Issue by RtYkk** [ClearURLs/Addon#188]
![chrome_k6hIyXD8As](https://user-images.githubusercontent.com/45971730/160234619-3758df4d-c761-4fae-b097-e537b61506ef.png)
I've tested one by one and I can confirm that this is caused by ClearURLs

**Comment by KevinRoebert** [comment]
Did you also test with the newest version 1.24.1?

**Comment by RtYkk** [comment]
@KevinRoebert Fixed, thx. But this version has not been published to chrome webstore. I will wait for an official update.

**Comment by KevinRoebert** [comment]
I know. It can take up to a week until a new version is approved

**Comment by bacteriostat** [comment]
The latest published update also broke ads.google.com and aws.amazon.com for me. I have disabled the extension for now.

**Comment by hackguy25** [comment]
1.24.0 also broke Spotify web player, 1.24.1 fixes it.

**Comment by MichalSvatos** [comment]
The same is happening with Slack ...
![slack](https://user-images.githubusercontent.com/5910531/160241590-f32d16ec-bd16-44ca-8367-14cdc4570230.jpg)

**Comment by KevinRoebert** [comment]
> The same is happening with Slack ...
> 
> ![slack](https://user-images.githubusercontent.com/5910531/160241590-f32d16ec-bd16-44ca-8367-14cdc4570230.jpg)
> 
> 

Which version of ClearURLs?

**Comment by Marat-Tanalin** [comment]
Yandex Mail broke (main mail interface does not open, the “Page does not exist” error is displayed) ~two days ago (apparently exactly when ClearURLs 1.24.1 was released).

The reason is apparently that `=` character is somehow added to the `#inbox` anchor/hash in the URL. Disabling the addon solves the issue. Does not happen with a new profile or another browser too.

* Correct URL (without ClearURLs addon):  
  `https://mail.yandex.ru/?uid=1234567#inbox`

* Incorrect URL (with ClearURLs addon):  
  `https://mail.yandex.ru/?uid=1234567#inbox=`

**Comment by MichalSvatos** [comment]
> > The same is happening with Slack ...
> 
> Which version of ClearURLs?
1.24.0

Today I checked and 1.24.1 seems to fix the problem.

**Comment by bacteriostat** [comment]
Yes, 1.24.1 has landed and the websites are no more broken.

**Comment by RtYkk** [comment]
I'll close this issue since 1.24.1 has landed.

**Comment by Marat-Tanalin** [comment]
But it’s exactly 1.24.1 that breaks Yandex Mail. Should I file a new issue?

**Comment by Marat-Tanalin** [comment]
What log?

**Comment by KevinRoebert** [comment]
> What log?

Here you can find a step by step tutorial "How to enable logging in ClearURLs": https://www.youtube-nocookie.com/embed/Rm1YkwXQDSM
