### ISSUE TITLE
I think it is time to fork this extension to have updates...

### ISSUE THREAD

**Issue by Neustradamus** [ClearURLs/Addon#330]
Dear all,

I think it is time to fork this extension to have updates...

What do you think?

Linked to:
- https://github.com/ClearURLs/Rules/issues/93 + https://gitlab.com/ClearURLs/rules/-/issues/293
- https://github.com/ClearURLs/Addon/issues/330 + https://gitlab.com/ClearURLs/ClearUrls/-/issues/1285
- https://gitlab.com/ClearURLs/rules/-/merge_requests/48
- https://github.com/ClearURLs/Addon/issues/314 + https://gitlab.com/ClearURLs/ClearUrls/-/issues/1276
- https://github.com/ClearURLs/Rules/issues/85 + https://gitlab.com/ClearURLs/rules/-/issues/283
- ...

**Comment by FuccDucc** [comment]
It's clear that this plugin/repository is largely abandoned. Crucial and easy to fix issues do not get fixed, PR's to address such issues dont get handled, and there is an overall lack of development & update pace, as a result of which we're currently in the situation that many links no longer get properly cleared.

@Neustradamus as i see it, you wanted to open this subject for an opportunity to them to remain as the main plugin, by picking up where they left, or to find out whether or not this was likely to happen, before a fork. Clearly, they don't want to hear about or discuss this, because they locked your other issue #93 when the discussion got too real and it began to show the abandoned state of this project currently.

Now, as an avid user of this plugin, i have to agree with you that someone needs to take over by forking it, and becoming the main project based on ClearURLs, but not in abandonment, with regular updates and neccesary changes to keep the plugin functioning as per its intended design. Even if they lock this # too, i hope someone makes a move and forks it.
