### ISSUE TITLE
Add support to new Firefox for Android 79.0.0-beta

### ISSUE THREAD

**Issue by hsantanna** [ClearURLs/Addon#63]
Current add-on version doesn't support the new Firefox for Android.
Maybe it doesn't require much code change, only API version update. But I'm not sure.

**Comment by TuxKruger** [comment]
Any progress on this? Asking cuz I see that the dev reopened the issue.

**Comment by OJFord** [comment]
Firefox for Android now only supports Mozilla-hand-picked extensions; there are a total of 16 (here anyway, might vary between regions).

They are hand-picked from the 'recommended extensions programme'; which ClearURLs is in, so that's a start. I don't know where you go from there without a friend at Mozilla, though:

https://support.mozilla.org/en-US/kb/find-and-install-add-ons-firefox-android

There's also a request for similar functionality built into FF itself (which I assume would mean Android too); which is 'on our radar and roadmap but without a clear ETA':

https://bugzilla.mozilla.org/show_bug.cgi?id=1697982

**Comment by hsantanna** [comment]
I'm closing this bug since ClearURL already works with Firefox nightly for Android.

**Comment by OJFord** [comment]
Nice to hear @hsantanna, thanks! Look forward to seeing it available in the public/stable list.
